spring.application.name=backend-finanzas

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

firebase.project-id=${FIREBASE_PROJECT_ID}
firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH:classpath:firebase-service-account.json}
firebase.service-account-json=${FIREBASE_SERVICE_ACCOUNT_JSON:}

gemini.api.key=${GEMINI_API_KEY}
gemini.model={GEMINI_MODEL:gemini-2.5-flash}
gemini.temperature=${GEMINI_TEMPERATURE:0.2}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.unknow=${JWT_SECRET}
jwt.exp=${JWT_EXP:86400000}
